package com.github.martinfrank.eobedit.event;

public enum ChangeEventType {

    NAME, INVENTORY, STATS, EXP_LEVEL_FIRST, EXP_LEVEL_SECOND, EXP_LEVEL_THIRD, EXP_POINTS_FIRST, EXP_POINTS_SECOND,
    EXP_POINTS_THIRD, PROFESSION, RACE, ALIGNMENT, FOOD_LEVEL, PORTRAIT,

    LOAD_DATA
}
